package phase2;

public class Item {
	// 2.0 Second version of the code phase two
	// by Latifah

	
		
		private String name; 									//name of item 
		private String id;										//the ID of the item
		private double price;									//the cost of the item
		private String BookingInfo; 							// a String contains all booking info ( who booked and when )
		private double profit;									 // Accumulates the total profit generated by this item
		private int numberOfBooking	;							//store the number of bookings for this item. 
		public static int numberOfItems;						//Tracks the number of instantiated items.
		public static double TotalProfit;						//Accumulates the total profit generated from all items.
		
		public Item() {
			
		}
		
		public Item(String name, String id, double price) {
			
		}
		
		private boolean isDateAvaliable (int day, int month, int year) {
			if(true)//Ø§Ù„Ø´Ø±Ø· ØºÙ„Ø· Ø¨Ø³ Ø¹Ø´Ø§Ù† Ù…Ø§ ÙŠØµÙŠØ± ÙÙŠÙ‡ Ø§ÙŠØ±ÙˆØ±
				return true;
			else 
				return false;
		}
		public boolean book(String CustomerID, String name, int day, int month, int year ) {
			if (true)//Ø§Ù„Ø´Ø±Ø· ØºÙ„Ø· Ø¨Ø³ Ø¹Ø´Ø§Ù† Ù…Ø§ ÙŠØµÙŠØ± ÙÙŠÙ‡ Ø§ÙŠØ±ÙˆØ±
				return true;
			else 
				return false;
				
		}
		public boolean cancel(String CustomerID, String name, int day, int month, int year) {
			if (true)//Ø§Ù„Ø´Ø±Ø· ØºÙ„Ø· Ø¨Ø³ Ø¹Ø´Ø§Ù† Ù…Ø§ ÙŠØµÙŠØ± ÙÙŠÙ‡ Ø§ÙŠØ±ÙˆØ±
				return true;
			else 
				return false;
		}
		public int getNumberOfBooking() {
			
			return numberOfBooking;//Ø§Ù„Ø´Ø±Ø· ØºÙ„Ø· Ø¨Ø³ Ø¹Ø´Ø§Ù† Ù…Ø§ ÙŠØµÙŠØ± ÙÙŠÙ‡ Ø§ÙŠØ±ÙˆØ±

		}
		
		public void printInfo() {

		}

		public void setName(String newName) {
			name = newName;
		}

		public String getName() {
			return name;
		}

		public void setId(String newId) {
			id = newId;
		}

		public String getId() {
			return id;
		}

		public void setPrice(double newPrice) {
			price = newPrice;
		}

		public double getPrice() {
			return price;
		}

		public void setBookingInfo(String newBookingInfo) {
			BookingInfo = newBookingInfo;
		}

		public String getBookingInfo() {
			return BookingInfo;
		}

		public double getProfit() {
			return profit;
		}

		public static int getNumberOfItems() {
			return numberOfItems;
		}

		public static double getTotalProfit() {
			return TotalProfit;
		}
		
		
		
		

	}//end class


	
	

